# docker-compose.yml
services:
  db:
    image: postgres:16
    container_name: bookapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookapp"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    container_name: bookapp-api
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:

